### ISSUE TITLE
Handle booleans like strings

### ISSUE THREAD

**Issue by djsegal** [piever/InteractBulma.jl#18]
Sometimes I make a quick boolean array in an interact tool:

```
@manipulate for foo=[true,false]
  foo ? "fizz" : "buzz"
end
```

The problem is it treats `true` and `false` and numbers (i.e. with a slider)

-------

Is there a way to handle them like strings (i.e. with toggle buttons)

<img width="819" alt="screen shot 2018-08-02 at 2 49 35 pm" src="https://user-images.githubusercontent.com/3156114/43604636-45ba799c-9664-11e8-9847-defd8006a454.png">

**Comment by piever** [comment]
Concerning the `@manipulate` bug, `@manipulate` is a bit undocumented but to get a toggle switch you can use:
```julia
@manipulate for woof = true
...
```

Now `OrderedDict` translates to togglebuttons, `Bool` translates to toggle switch, non-numeric `AbstractArray` translates to togglebuttons whereas numeric `AbstractArray` translates to `slider`. Though I had forgotten that `Bool<:Number`...

If rather than a toggle you prefer two togglebuttons, you can explicitly pass the `OrderedDict`:

```julia
using DataStructures
@manipulate for woof in OrderedDict("true" => true, "false" => false)
...
```
This is a bit cumbersome, but I guess I can restore the boolean array to do togglebuttons, though I really think a toggle switch makes more sense for boolean choices.

In any case, another option is to use the widget directly:

```julia
@manipulate for woof in togglebuttons([true, false], label = ...)
```
